spring.application.name=ad-service
server.port=${SERVER_PORT}

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${USERNAME}
spring.datasource.password=${PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
eureka.client.service-url.defaultZone=${EUREKA_URL}
logging.level.root=INFO
logging.level.com.example.user_service=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

spring.kafka.bootstrap-servers=${KAFKA_URL}

spring.kafka.consumer.group-id=ad-service
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.timeout=60000
spring.data.redis.database=${REDIS_DB_AD}